### PR TITLE
Remove-attachments-bug fix

### PR DESCRIPTION
**Pull request by KamilaHasanbega**
Addressed the #27 issue, of removing the wrong attachment.

### CODE REVIEW

**Comment by koto** [comment]
So this is not needed if #28 is merged? If you want to submit this one separately, please see my comments on #28 re: attachments removal.

**Comment by KamilaHasanbega** [comment]
@koto The CL is needed because it changes the messages controller while #28 changes the threads controller and its UI.

**Comment by koto** [comment]
LGTM, safe to merge @kbsriram

**Comment by kbsriram** [comment]
Rebased via 3a17b4a

**Pull request closed without merging**
